In [5]:
import pandas as pd
import sys
from pathlib import Path

# Add the root directory to the system path
sys.path.append(str(Path().resolve().parent))

from preprocessing.amharic_text_cleaner import clean_amharic_text

In [6]:
input_path = "../data/raw/telegram_data.xlsx"

df = pd.read_excel(input_path)
df = df[['Channel Title', 'Message']].dropna().copy()
df.head()

          Channel Title                                            Message
5   Sheger online-store  💥3pcs silicon brush spatulas\n\n⚡እስከ 260°c ሙቀት...
6   Sheger online-store  💥Mandoline Slicer\n\n👉 ጊዜ ቆጣቢ ስላይስ ማድረጊያ \n👉  ...
7   Sheger online-store  💥Table Desk Edge Guard Strip\n       💯 High Qu...
8   Sheger online-store  💥Table Desk Edge Guard Strip\n       💯 High Qu...
10  Sheger online-store  💥Only baby 3in1 double bottle milk warmer,ster...

In [7]:
df['Cleaned_Message'] = df['Message'].astype(str).apply(clean_amharic_text)
df[['Message', 'Cleaned_Message']].head(10)

,Message,Cleaned_Message
5,💥3pcs silicon brush spatulas\n\n⚡እስከ 260°c ሙቀት...,3pcs silicon brush spatulas እስከ 260c ሙቀት መቆቆም ...
6,💥Mandoline Slicer\n\n👉 ጊዜ ቆጣቢ ስላይስ ማድረጊያ \n👉 ...,Mandoline Slicer ጊዜ ቆጣቢ ስላይስ ማድረጊያ ለእጅ ሴፍቲ ተመራ...
7,💥Table Desk Edge Guard Strip\n 💯 High Qu...,Table Desk Edge Guard Strip High Quality Made ...
8,💥Table Desk Edge Guard Strip\n 💯 High Qu...,Table Desk Edge Guard Strip High Quality Made ...
10,"💥Only baby 3in1 double bottle milk warmer,ster...","Only baby 3in1 double bottle milk warmer,steri..."
11,"💥Only baby 3in1 double bottle milk warmer,ster...","Only baby 3in1 double bottle milk warmer,steri..."
14,💥1pc stainless steel loaf pan\n\n👍ትልቁ\n\n ...,1pc stainless steel loaf pan ትልቁ ዋጋትልቁ800ብር ውስ...
16,📣Geemy Rechargable Hair Clipper\n\n✔️ የፀጉርና የ...,Geemy Rechargable Hair Clipper የፀጉርና የፂም መቁረጪያ...
19,💥 kids water bottle\n\n 👉ጠንካራ እና እማይሰበር\n\n ...,kids water bottle ጠንካራ እና እማይሰበር ዋጋ450ml600ብር...
20,💥4Pcs isolated lunch box with bag \n\n⚡️በውስጡ 4...,4Pcs isolated lunch box with bag በውስጡ 4 የምሳ ዕቃ...

In [9]:
output_path = '../data/processed/cleaned_telegram_data.csv'

df.to_csv(output_path, index=False, encoding='utf-8')
print(f"[✓] Cleaned data saved to {output_path}")

[✓] Cleaned data saved to ../data/processed/cleaned_telegram_data.csv